[![pages-build-deployment](https://github.com/WhoisNeon/MaterialYouNewTab/actions/workflows/pages/pages-build-deployment/badge.svg)](https://github.com/WhoisNeon/MaterialYouNewTab/actions/workflows/pages/pages-build-deployment)
